#!/usr/bin/env dart

import 'dart:convert';
import 'package:rgnets_fdk/core/services/mock_data_service.dart';
import 'package:rgnets_fdk/features/devices/data/datasources/device_mock_data_source.dart';
import 'package:rgnets_fdk/core/config/environment.dart';

void main() async {
  print('=' * 80);
  print('MOCK DATA FLOW DEBUG');
  print('=' * 80);
  
  // Set environment to development
  EnvironmentConfig.setEnvironment(Environment.development);
  print('\n1. Environment: ${EnvironmentConfig.environment}');
  print('   isDevelopment: ${EnvironmentConfig.isDevelopment}');
  print('   useSyntheticData: ${EnvironmentConfig.useSyntheticData}');
  
  // Create MockDataService
  print('\n2. Creating MockDataService...');
  final mockService = MockDataService();
  
  // Get raw Device objects
  print('\n3. Raw Device objects from MockDataService:');
  final devices = mockService.getMockDevices();
  print('   Total devices: ${devices.length}');
  
  // Show first few of each type
  final aps = devices.where((d) => d.type == 'access_point').take(3).toList();
  print('\n   Access Points (first 3):');
  for (final ap in aps) {
    print('     ID: ${ap.id.padRight(10)} Name: ${ap.name}');
  }
  
  final switches = devices.where((d) => d.type == 'switch').take(3).toList();
  print('\n   Switches (first 3):');
  for (final sw in switches) {
    print('     ID: ${sw.id.padRight(10)} Name: ${sw.name}');
  }
  
  final onts = devices.where((d) => d.type == 'ont').take(3).toList();
  print('\n   ONTs (first 3):');
  for (final ont in onts) {
    print('     ID: ${ont.id.padRight(10)} Name: ${ont.name}');
  }
  
  // Get JSON that will be parsed
  print('\n4. JSON generated by MockDataService:');
  
  final apJson = mockService.getMockAccessPointsJson();
  print('\n   Access Points JSON:');
  final apResults = apJson['results'] as List<dynamic>;
  print('   Total in JSON: ${apResults.length}');
  for (final ap in apResults.take(3)) {
    print('     ID: ${ap['id']} Name: "${ap['name']}"');
  }
  
  final switchJson = mockService.getMockSwitchesJson();
  print('\n   Switches JSON:');
  final switchResults = switchJson['results'] as List<dynamic>;
  print('   Total in JSON: ${switchResults.length}');
  for (final sw in switchResults.take(3)) {
    print('     ID: ${sw['id']} Name: "${sw['name']}" (nickname: "${sw['nickname']}")');
  }
  
  final ontJson = mockService.getMockMediaConvertersJson();
  print('\n   ONTs JSON:');
  final ontResults = ontJson['results'] as List<dynamic>;
  print('   Total in JSON: ${ontResults.length}');
  for (final ont in ontResults.take(3)) {
    print('     ID: ${ont['id']} Name: "${ont['name']}"');
  }
  
  // Parse through DeviceMockDataSourceImpl
  print('\n5. After parsing by DeviceMockDataSourceImpl:');
  final mockDataSource = DeviceMockDataSourceImpl(
    mockDataService: mockService,
  );
  
  final deviceModels = await mockDataSource.getDevices();
  print('   Total DeviceModels: ${deviceModels.length}');
  
  final apModels = deviceModels.where((d) => d.type == 'access_point').take(3).toList();
  print('\n   Access Point Models (first 3):');
  for (final model in apModels) {
    print('     ID: ${model.id.padRight(15)} Name: ${model.name}');
  }
  
  final switchModels = deviceModels.where((d) => d.type == 'switch').take(3).toList();
  print('\n   Switch Models (first 3):');
  for (final model in switchModels) {
    print('     ID: ${model.id.padRight(15)} Name: ${model.name}');
  }
  
  final ontModels = deviceModels.where((d) => d.type == 'ont').take(3).toList();
  print('\n   ONT Models (first 3):');
  for (final model in ontModels) {
    print('     ID: ${model.id.padRight(15)} Name: ${model.name}');
  }
  
  // Analyze the problem
  print('\n6. ANALYSIS:');
  print('=' * 80);
  
  // Check if names are preserved correctly
  bool namesMatch = true;
  
  for (int i = 0; i < 3 && i < aps.length; i++) {
    final originalName = aps[i].name;
    final jsonName = apResults[i]['name'];
    final modelName = apModels[i].name;
    
    if (originalName != jsonName || jsonName != modelName) {
      namesMatch = false;
      print('\n   MISMATCH FOUND for AP ${i + 1}:');
      print('     Original Device.name: "$originalName"');
      print('     JSON name field:      "$jsonName"');
      print('     Final Model.name:     "$modelName"');
    }
  }
  
  if (namesMatch) {
    print('\n   ✓ Names are preserved correctly through the data flow');
  } else {
    print('\n   ✗ Names are NOT being preserved correctly');
  }
  
  // Check format
  print('\n7. FORMAT CHECK:');
  if (apModels.isNotEmpty) {
    final name = apModels.first.name;
    print('   First AP name: "$name"');
    
    if (name.matches(RegExp(r'^AP\d-\d-\d{4}-[A-Z0-9]+-RM\d+[A-Z]?$'))) {
      print('   ✓ Matches production format: AP[building]-[floor]-[serial]-[model]-RM[room]');
    } else {
      print('   ✗ Does NOT match production format');
      print('   Expected: AP1-2-0030-AP520-RM205');
      print('   Got:      $name');
    }
  }
  
  print('\n' + '=' * 80);
  print('END OF DEBUG');
  print('=' * 80);
}

extension on String {
  bool matches(RegExp pattern) => pattern.hasMatch(this);
}